version: '3.8'
services:
  react_calculator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react_calculator_app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
